###
GET http://localhost:8080/api/v1/order

###
GET http://localhost:8080/api/v1/product

###
GET http://localhost:8080/api/v1/product?owner=6464d3155ded8d052d323c2a

###
GET http://localhost:8080/api/v1/product

###
GET http://localhost:8080/api/v1/profile

###

GET http://localhost:8080/api/v1/profile/6464d3155ded8d052d323c2a

###
GET http://localhost:8080/api/v1/address

###
GET http://localhost:8080/api/v1/paymentmethod

###
GET http://localhost:8080/api/v1/conversation

###
GET http://localhost:8080/api/v1/conversation/646a5aee4e38042c9c199a67

###
GET http://localhost:8080/api/v1/profile/username/paola
###
GET http://localhost:8080/api/v1/profile/username/margheritaepietro
