version: '3.9'
services:
  client:
    build:
      context: .
      dockerfile: Dockerfile
    command: sh -c "npm start"
    ports:
      - 4200:4200
    working_dir: /home/node/app
    volumes:
      - ./:/home/node/app
    network_mode: "host"
